<?php
require '../../includes/db-config.php';
require '../../includes/helpers.php';
session_start();

$url = "https://erpglocal.iitseducation.org";
$passFail = "PASS";

use setasign\Fpdi\PdfReader;
use setasign\Fpdi\Fpdi;

ob_end_clean();
require_once('../../extras/TCPDF/tcpdf.php');
require_once('../../extras/vendor/setasign/fpdf/fpdf.php');
require_once('../../extras/vendor/setasign/fpdi/src/autoload.php');
require '../../extras/vendor/autoload.php';
$sqlQuery = '';
if (isset($_POST['course_type_id']) && !empty($_POST['course_type_id'])) {
    $course_id = $_POST['course_type_id'];
    $sqlQuery .= "AND Students.Course_ID = '$course_id'";
}

if (isset($_POST['course_id']) && !empty($_POST['course_id'])) {
    $sub_course_id = $_POST['course_id'];
    $sqlQuery .= " AND Students.Sub_Course_ID = '$sub_course_id'";
}

if (isset($_POST['student_id']) && !empty($_POST['student_id'])) {
    $student_id_array = explode(",", $_POST['student_id']);
    foreach ($student_id_array as &$en_no) {
        $en_no = "'" . $en_no . "'";
    }
    unset($en_no);
    $student_id = implode(",", $student_id_array);
    $sqlQuery .= " AND Students.Enrollment_No IN ($student_id)";
}

if (isset($_POST['category']) && !empty($_POST['category'])) {
    $sub_course_id = $_POST['category'];
    $sqlQuery .= " AND Students.Duration = '$sub_course_id'";
}

$pdf_dir = '../../uploads/marksheet/';

$student = $conn->query("SELECT Students.*, Sub_Courses.Min_Duration as total_duration, Modes.Name as mode, Sub_Courses.Name as course, Courses.Name as program_Type FROM Students LEFT JOIN Sub_Courses ON Sub_Courses.ID = Students.Sub_Course_ID LEFT JOIN Modes ON Students.University_ID = Modes.University_ID LEFT JOIN Courses ON Students.Course_ID = Courses.ID  WHERE Students.Enrollment_No IS NOT NULL $sqlQuery");

if ($student->num_rows > 0) {
    while ($row = $student->fetch_assoc()) {
        $students_result = $conn->query("SELECT Students.*, Sub_Courses.Min_Duration as total_duration, Modes.Name as mode, Sub_Courses.Name as course, Courses.Name as program_Type FROM Students LEFT JOIN Sub_Courses ON Sub_Courses.ID = Students.Sub_Course_ID LEFT JOIN Modes ON Students.University_ID = Modes.University_ID LEFT JOIN Courses ON Students.Course_ID = Courses.ID  WHERE Students.Enrollment_No = '" . trim($row['Enrollment_No']) . "'");

        $data = [];
        $data['remarks'] = "Pass";
        $data = $students_result->fetch_assoc();
        $typoArr = ["th", "st", "nd", "rd", "th", "th", "th", "th", "th"];

        $total_obt = 0;
        $total_max = 0;
        $html_marks = '';
        $durations_query = "";
        if ($data['University_ID'] == 47) {
            $durations_query = " AND Syllabi.Semester = " . $data['Duration'];
        }
        $total_obt = 0;
        $total_max = 0;
        $min_val = 0;
        $temp_subjects = "";

        if ($data['University_ID'] == 48) {
            $temp_subjects = $conn->query("SELECT marksheets.obt_marks_ext, marksheets.obt_marks_int,marksheets.obt_marks,marksheets.status,marksheets.remarks,marksheets.Created_At,Syllabi.Code,Syllabi.Name as subject_name,Syllabi.Min_Marks, Syllabi.Max_Marks FROM marksheets LEFT JOIN Syllabi ON marksheets.subject_id = Syllabi.ID WHERE enrollment_no = '" . $data['Enrollment_No'] . "' ");
        } else {
            $temp_subjects = $conn->query("SELECT marksheets.obt_marks_ext, marksheets.obt_marks_int,marksheets.obt_marks,marksheets.status,marksheets.remarks,marksheets.Created_At, Syllabi.Code,Syllabi.Name as subject_name,Syllabi.Min_Marks, Syllabi.Max_Marks FROM marksheets LEFT JOIN Syllabi ON marksheets.subject_id = Syllabi.ID WHERE enrollment_no = '" . $data['Enrollment_No'] . "' AND Semester = $sem ");
        }

        $data['marks'] = array();
        $temp_subject = [];

        $resultPublishDay = "";
        if ($temp_subjects->num_rows > 0) {
            while ($temp_subject = $temp_subjects->fetch_assoc()) {

                if ($temp_subject != null) {
                    $resultPublishDay = date("d/m/Y", strtotime($temp_subject['Created_At']));
                    $temp_subject['remarks'] = isset($data['remarks']) ? $data['remarks'] : '';

                    $obt_marks_ext = isset($temp_subject['obt_marks_ext']) ? $temp_subject['obt_marks_ext'] : 0;
                    $obt_marks_int = isset($temp_subject['obt_marks_int']) ? $temp_subject['obt_marks_int'] : 0;
                    $total_obt = $total_obt + $obt_marks_ext + $obt_marks_int;
                    $min_val = ($temp_subject['Min_Marks'] + $temp_subject['Max_Marks']) * 40 / 100;
                    $passFail = "Pass";
                    if ($total_obt < $min_val) {
                        $passFail = "FAIL";
                    }

                    if ($data['University_ID'] == 47) {
                        $total_max = $total_max + $temp_subject['Min_Marks'] + $temp_subject['Max_Marks'];
                    } else {
                        $total_max = $total_max + $temp_subject['Max_Marks'];
                    }
                    $temp_subject['remarks'] = $passFail;
                    $data['marks'][] = $temp_subject;
                    $data['remarks'] = $passFail;
                }
            }

            $data['total_max'] = $total_max;
            $data['total_obt'] = $total_obt;
            $percentage = 0;
            if ($total_max !== 0) {
                $percentage = ($total_obt / $total_max) * 100;
            } else {
                $percentage = 0;
            }

            $marksWords = ucwords(strtolower(numberToWordFunc($total_obt)));

            $count = $temp_subjects->num_rows;
            if ($data['University_ID'] == 48) {
                $data['university_name'] = "Skill Education Development";
            } else {
                $data['university_name'] = "Glocal School Of Vocational Studies";
            }
            $hours = '';
            $total_duration = '';

            if ($data['University_ID'] == 48) {
                $data['mode_type'] = "Duration";
                $total_duration = $data['Duration'];
                $data['Durations'] = $data['Duration'];
                if ($total_duration == 3) {
                    $durations = "Certification Course";
                    $hours = 160;
                } elseif ($total_duration == 6) {
                    $durations = "Certified Skill Diploma";
                    $hours = 320;
                } else if ($data['Duration'] == '11/advance-diploma') {
                    $hours = 960;
                    $durations = "Adv. Certification Skill Diploma";
                    $data['Durations'] = 11;
                } else if ($data['Duration'] == '11/certified') {
                    $durations = "Certified Skill Diploma";
                    $data['Durations'] = 11;
                    $hours = 960;
                } elseif ($total_duration == 6 && $durMonthYear == "Semester") {
                    $hours = 'NA';
                }
            } else {
                $data['mode_type'] = "Semester";
            }

            $data['duration_val'] = $durations;

            $durMonthYear = "";
            if ($data['mode'] == "Monthly") {
                $durMonthYear = " Months";
            } elseif ($data['mode'] == "Sem") {
                $durMonthYear = " Semester";
            } else {
                $durMonthYear = " Years";
            }

            if ($data['University_ID'] == 48) {
                $data['mode_type'] = "Duration";
            } else {
                $data['mode_type'] = "Semester";
            }
            if ($data['University_ID'] == 48) {
                $data['durMonthYear'] = $data['Durations'] . $durMonthYear . '/ ' . $hours . "Hours";
            } else {
                $data['durMonthYear'] = $data['Duration'] . $typoArr[$data['Duration']];
            }
            $student_doc_query = "SELECT Location FROM Student_Documents WHERE Student_ID = '" . $data['ID'] . "' AND Type = 'Photo'";
            $student_doc = $conn->query($student_doc_query);
            $student_doc = $student_doc->fetch_assoc();
            $photo = $student_doc['Location'];
            $data['Photo'] = $url . $photo;

            $pdf = new Fpdi();
            $pdf->addPage();
            $pdf->SetFont("times", '', 10);
            $pdf->SetXY(15, 65);
            $pdf->Cell(0, 0, 'Statement of Marks', 0, 0, 'C', 0);
            $pdf->SetXY(15, 72.4);
            $pdf->Cell(0, 0, $data['duration_val'] . ' ' . 'in' . ' ' . $data['course'], 0, 0, 'C', 0);
            $pdf->SetXY(15, 81);
            $pdf->Cell(0, 0, 'AY  2023-24' . '', 0, 0, 'C', 0);
            $pdf->SetXY(16.1, 86);
            $pdf->Cell(107, 10, 'Name : ' . ucwords(strtolower($data['First_Name'])) . ' ' . ucwords(strtolower($data['Middle_Name'])) . ' ' . ucwords(strtolower($data['Last_Name'])), 'TL', 0, 'L', 0);
            $pdf->SetXY(123, 86);
            $pdf->Cell(70, 10, 'Enrollment No : ' . $data['Enrollment_No'], 'LTR', 0, 'L', 0);
            $pdf->SetXY(16.1, 96);
            $pdf->Cell(107, 10, 'School : ' . 'School Of' . ' ' . $data['university_name'], 'LTB', 0, 'L', 0);
            $pdf->SetXY(123, 96);
            $pdf->Cell(70, 10, $data['mode_type'] . ' ' . ':' . ' ' . $data['durMonthYear'], 1, 0, 'L', 0);

            // skill
            $pdf->SetFont('Arial', 'B', 10);
            $cellWidth = 20;
            $cellHeight = 10;
            $pdf->SetXY(16.1, 110);
            $pdf->MultiCell(25, 10, 'Subject Code', 'TLB', 'C');
            $pdf->SetXY(41, 110);
            $pdf->MultiCell(71, 10, 'Subject Name ', 'TLB', 'C');
            $pdf->SetXY(112, 110);
            $pdf->MultiCell(20, 5, 'Obtained Marks', 'TLB', 'C');
            $pdf->SetXY(132, 110);
            $pdf->MultiCell(20, 5, 'Min. Marks', 'TLB', 'C');
            $pdf->SetXY(152, 110);
            $pdf->MultiCell(19.8, 5, 'Max. Marks', 'TLB', 'C');
            $pdf->SetXY(172, 110);
            $pdf->MultiCell(22, 10, 'Remarks', 1, 'C');
            $pdf->SetXY(10, 110);
            $pdf->Ln();

            $pdf->SetFont('Arial', '', 10);
            $x_cor = 16;
            $pdf->SetX($x_cor);
            foreach ($data['marks'] as $mark) {
                $pdf->SetX($x_cor);
                if (strlen($mark['subject_name']) > 30) {
                    $cellHeight = 20;
                } else {
                    $cellHeight = 10;
                }
                if (strlen($mark['subject_name']) > 30) {
                    $pdf->Cell(25, $cellHeight - 10, $mark['Code'], 'LB', 0, 'L');
                    $nameParts = explode("\n", wordwrap($mark['subject_name'], 30));
                    $pdf->MultiCell(71, 5, $nameParts[0] . chr(10) . $nameParts[1], 'LB', 0, 0, 'L');
                    $x = $pdf->GetX();
                    $y = $pdf->GetY();
                    $pdf->SetXY($x + 102, $y - 10);
                    $pdf->Cell($cellWidth, $cellHeight - 10, $mark['obt_marks'], 'LB', 0, 'C');
                    $pdf->Cell($cellWidth, $cellHeight - 10, $mark['Min_Marks'], 'LB', 0, 'C');
                    $pdf->Cell($cellWidth, $cellHeight - 10, $mark['Max_Marks'], 'LB', 0, 'C');
                    $pdf->Cell(22, $cellHeight - 10, $mark['remarks'], 'LBR', 0, 'C');
                } else {
                    $pdf->Cell(25, $cellHeight, $mark['Code'], 'LB', 0, 'L');
                    $pdf->Cell(71, $cellHeight, $mark['subject_name'], 'LB', 0, 'L');
                    $pdf->Cell($cellWidth, $cellHeight, $mark['obt_marks'], 'LB', 0, 'C');
                    $pdf->Cell($cellWidth, $cellHeight, $mark['Min_Marks'], 'LB', 0, 'C');
                    $pdf->Cell($cellWidth, $cellHeight, $mark['Max_Marks'], 'LB', 0, 'C');
                    $pdf->Cell(22, $cellHeight, $mark['remarks'], 'LBR', 0, 'C');
                }
                $pdf->Ln();
            }

            if ($count >= 9) {
                //more thwn 9 subject
                $pdf->SetXY(16, 234.4);
                $pdf->SetFont('Arial', 'B', 10);
                $pdf->Cell(0, 0, 'Aggregate Marks', 0, 0, 'C', 0);
                $pdf->SetXY(16, 238.4);
                $pdf->Cell(65, 8, 'Marks', 'TL', 1, 'C', 0);
                $pdf->SetXY(81, 238.4);
                $pdf->Cell(35, 8, 'Grand Total', 'TL', 1, 'C', 0);
                $pdf->SetXY(116, 238.4);
                $pdf->Cell(35, 8, 'Result', 'LTB', 1, 'C', 0);
                $pdf->SetXY(151, 238.4);
                $pdf->Cell(42, 8, 'Percentage', 1, 1, 'C', 0);
                $pdf->SetFont('Arial', '', 10);
                $pdf->SetXY(16, 246.4);
                $pdf->Cell(65, 8, ' Obtained Mark', 'TL', 1, 'C', 0);
                $pdf->SetXY(81, 246.4);
                $pdf->Cell(35, 8, $data['total_obt'], 'TL', 1, 'C', 0);
                $pdf->SetXY(116, 246.4);
                $pdf->Cell(35, 8, $data['remarks'], 'TLR', 1, 'C', 0);
                $pdf->SetXY(151, 246.4);
                $pdf->Cell(42, 8, number_format($percentage, 2) . "%", 'TR', 1, 'C', 0);
                $pdf->SetXY(16, 254.3);
                $pdf->Cell(65, 8, 'Maximum Mark', 'TLB', 1, 'C', 0);
                $pdf->SetXY(81, 254.3);
                $pdf->Cell(35, 8, $data['total_max'], 'LBT', 1, 'C', 0);
                $pdf->SetXY(116, 254.3);
                $pdf->Cell(35, 8, '', 'LRB', 'LB', 'C', 0);
                $pdf->SetXY(151, 254.3);
                $pdf->Cell(42, 8, '', 'RB', 'RB', 'C', 0);
            } else {
                //less then 9 subject
                $pdf->SetXY(16, 217.4);
                $pdf->SetFont('Arial', 'B', 10);
                $pdf->Cell(0, 0, 'Aggregate Marks', 0, 0, 'C', 0);
                $pdf->SetXY(16, 221.4);
                $pdf->Cell(65, 8, 'Marks', 'TL', 1, 'C', 0);
                $pdf->SetXY(81, 221.4);
                $pdf->Cell(35, 8, 'Grand Total', 'TL', 1, 'C', 0);
                $pdf->SetXY(116, 221.4);
                $pdf->Cell(35, 8, 'Result', 'LTB', 1, 'C', 0);
                $pdf->SetXY(151, 221.4);
                $pdf->Cell(42, 8, 'Percentage', 1, 1, 'C', 0);
                $pdf->SetFont('Arial', '', 10);
                $pdf->SetXY(16, 229.4);
                $pdf->Cell(65, 8, ' Obtained Mark', 'TL', 1, 'C', 0);
                $pdf->SetXY(81, 229.4);
                $pdf->Cell(35, 8, $data['total_obt'], 'TL', 1, 'C', 0);
                $pdf->SetXY(116, 229.4);
                $pdf->Cell(35, 8, $data['remarks'], 'TLR', 1, 'C', 0);
                $pdf->SetXY(151, 229.4);
                $pdf->Cell(42, 8, number_format($percentage, 2) . "%", 'TR', 1, 'C', 0);
                $pdf->SetXY(16, 237.3);
                $pdf->Cell(65, 8, 'Maximum Mark', 'TLB', 1, 'C', 0);
                $pdf->SetXY(81, 237.3);
                $pdf->Cell(35, 8, $data['total_max'], 'LBT', 1, 'C', 0);
                $pdf->SetXY(116, 237.3);
                $pdf->Cell(35, 8, '', 'LRB', 'LB', 'C', 0);
                $pdf->SetXY(151, 237.3);
                $pdf->Cell(42, 8, '', 'RB', 'RB', 'C', 0);
            }

            $filename = $data['Enrollment_No'] . "_" . time() . ".pdf";
            $pdf->Output($pdf_dir . $filename, "F");
        }
    }

    $zip = new ZipArchive();
    $zip_file = $pdf_dir . 'Marksheets_' . time() . '.zip';
    if ($zip->open($zip_file, ZipArchive::CREATE | ZipArchive::OVERWRITE) === TRUE) {
        $files = glob($pdf_dir . '*.pdf');
        foreach ($files as $file) {
            $zip->addFile($file, basename($file));
        }
        $zip->close();

        header('Content-Type: application/zip');
        header('Content-disposition: attachment; filename=' . basename($zip_file));
        header('Content-Length: ' . filesize($zip_file));
        readfile($zip_file);

        foreach ($files as $file) {
            unlink($file);
        }
        unlink($zip_file);
    } else {
        echo 'Failed to create zip file.';
    }
} else {
    echo "No record found!";
}
